const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Physics,
		C3.Behaviors.Flash,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.NoSave,
		C3.Behaviors.LOS,
		C3.Plugins.Audio,
		C3.Behaviors.jumpthru,
		C3.Plugins.Mouse,
		C3.Plugins.Button,
		C3.Plugins.Text,
		C3.Behaviors.Turret,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.TileMovement,
		C3.Plugins.Browser,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.LOS.Acts.SetRange,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Turret.Acts.AcquireTarget,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Behaviors.Turret.Cnds.OnShoot,
		C3.Behaviors.TileMovement.Cnds.IsMovingDirection,
		C3.Behaviors.Platform.Acts.FallThrough,
		C3.Behaviors.Turret.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Tilemap.Acts.Destroy,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Button.Cnds.OnClicked
	];
};
self.C3_JsPropNameTable = [
	{fondo: 0},
	{Sólido: 0},
	{piso1: 0},
	{Plataforma: 0},
	{Físicas: 0},
	{Parpadeo: 0},
	{DesplazarHasta: 0},
	{RestringidoALaEscena: 0},
	{jugador: 0},
	{Teclado: 0},
	{Bala: 0},
	{DestruirFueraDeLaEscena: 0},
	{ataque: 0},
	{NoGuardar: 0},
	{LíneaDeVisión: 0},
	{enemigo: 0},
	{Audio: 0},
	{pisoizq: 0},
	{paredizq: 0},
	{paredder: 0},
	{pisoder: 0},
	{caja: 0},
	{aplasta: 0},
	{SaltoATravés: 0},
	{plataforma: 0},
	{dinero: 0},
	{bombs: 0},
	{Mouse: 0},
	{start: 0},
	{Sprite: 0},
	{FondoEnMosaico: 0},
	{creditos: 0},
	{vida1: 0},
	{vida2: 0},
	{vida3: 0},
	{mainMenu: 0},
	{Torreta: 0},
	{Buscarutas: 0},
	{MovimientoEnCuadrícula: 0},
	{miniboss: 0},
	{FondoEnMosaico2: 0},
	{Navegador: 0},
	{bala: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{VidaJugador: 0},
	{Score: 0},
	{VidaBoss: 0}
];

self.InstanceType = {
	fondo: class extends self.ITiledBackgroundInstance {},
	piso1: class extends self.ITilemapInstance {},
	jugador: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	ataque: class extends self.ISpriteInstance {},
	enemigo: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	pisoizq: class extends self.ITilemapInstance {},
	paredizq: class extends self.ITilemapInstance {},
	paredder: class extends self.ITilemapInstance {},
	pisoder: class extends self.ITilemapInstance {},
	caja: class extends self.ITilemapInstance {},
	aplasta: class extends self.ISpriteInstance {},
	plataforma: class extends self.ITilemapInstance {},
	dinero: class extends self.ISpriteInstance {},
	bombs: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	start: class extends self.IButtonInstance {},
	Sprite: class extends self.ISpriteInstance {},
	FondoEnMosaico: class extends self.ITiledBackgroundInstance {},
	creditos: class extends self.ITextInstance {},
	vida1: class extends self.ISpriteInstance {},
	vida2: class extends self.ISpriteInstance {},
	vida3: class extends self.ISpriteInstance {},
	mainMenu: class extends self.IButtonInstance {},
	miniboss: class extends self.ISpriteInstance {},
	FondoEnMosaico2: class extends self.ITiledBackgroundInstance {},
	Navegador: class extends self.IInstance {},
	bala: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {}
}